import Loading from "@/components/loadings/loading";

export const metadata = {
  title: "Zaloguj się na swoje konto w WorkHuner",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return (
    <div>
      <button className="btn btn-primary">Button</button>
    </div>
  );
};

export default LoginPage;
